[package]
name = "rework_ecoweb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
clap = { version = "4.5.2", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
mdtrans = "0.1.4"
mime_guess = "2.0.4"
parking_lot = "0.12.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
syntect = { version = "5.2.0", features = ["html", "regex-onig", "default-syntaxes", "default-themes"] }
tera = "1.19.1"
toml = "0.8.10"

[features]
default = [ "storage-local" ]
storage-local = []
