[package]
name = "ecoweb"
version = "0.1.0"
edition = "2021"

[dependencies]
# Software general
log = "0.4.20"
env_logger = "0.10.2"
parking_lot = "0.12.1"
clap = { version = "4.4.18", features = ["derive"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["macros", "fs"] }

# Data
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
chrono = "0.4.33"

# Filesystem
toml = "0.7.8"
fs_extra = "1.3.0"

# HTTP server
actix-files = "0.6.5"
actix-web = "4.4.1"
mime = "0.3.17"

# Web content manipulation
grass = "0.12.4"
tera = "1.19.1"
lightningcss = { version = "1.0.0-alpha.52", optional = true }
minify-html-onepass = { version = "0.11.5", optional = true }
minify-js = { version = "0.5.6", optional = true }
mdtrans = { git = "https://github.com/litchipi/mdtrans.git" }
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
awc = { version = "3.3.0", features = ["rustls"] }
zip = "0.6.6"
paste = "1.0.14"

[dependencies.syntect]
version = "5.1.0"
features = [ "html", "regex-onig", "default-themes", "default-syntaxes" ]
default-features = false

[features]
# Bundles
default = ["local_storage"]
dev = ["local_storage", "hot_reloading", "no_cache"]

# Extensions
save-data = []
add-endpoint = []
githook = []
rss = []
humans-txt = []
webring = []

# Minification
minify = ["css_minify", "html_minify", "js_minify"]
css_minify = ["lightningcss"]
html_minify = ["minify-html-onepass"]
js_minify = ["minify-js"]

# Storage
local_storage = []
hot_reloading = []
no_cache = []

[profile.release]
opt-level = 3
strip = "symbols"
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 4

[profile.dev]
codegen-units = 425 # 250
