[package]
name = "ecoweb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
env_logger = "0.10.0"
grass = "0.12.4"
log = "0.4.18"
serde = { version = "1.0.163", features = ["derive"] }
tera = "1.19.0"
toml = "0.7.4"
serde_json = "1.0.96"
comrak = "0.18.0"
regex = "1.8.4"
chrono = "0.4.26"
fs_extra = "1.3.0"
glob = { version = "0.3.1", optional = true}
lightningcss = { version = "1.0.0-alpha.42", optional = true }
minify-html-onepass = { version = "0.11.1", optional = true }
minify-js = { version = "0.5.6", optional = true }
futures-util = "0.3.28"
parking_lot = "0.12.1"
mime = "0.3.17"
clap = { version = "4.3.19", features = ["derive"] }
thiserror = "1.0.47"

[dependencies.syntect]
version = "5.0"
features = [ "html" ]
default-features = false

[features]
default = ["local_storage"]
dev = ["local_storage", "hot_reloading", "no_cache"]

local_storage = ["glob"]

minify = ["css_minify", "html_minify", "js_minify"]
css_minify = ["lightningcss"]
html_minify = ["minify-html-onepass"]
js_minify = ["minify-js"]

hot_reloading = []
no_cache = []

[profile.release]
opt-level = 3
strip = "symbols"
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 16

[profile.dev]
codegen-units = 425 # 250
