[package]
name = "ecoweb"
version = "0.1.0"
edition = "2021"

[dependencies]
# Software general
log = "0.4.18"
env_logger = "0.10.0"
parking_lot = "0.12.1"
clap = { version = "4.3.19", features = ["derive"] }
thiserror = "1.0.47"
tokio = { version = "1.34.0", features = ["macros"] }

# Data
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
chrono = "0.4.26"

# Filesystem
toml = "0.7.4"
fs_extra = "1.3.0"

# HTTP server
actix-files = "0.6.2"
actix-web = "4.3.1"
mime = "0.3.17"

# Web content manipulation
grass = "0.12.4"
tera = "1.19.0"
lightningcss = { version = "1.0.0-alpha.42", optional = true }
minify-html-onepass = { version = "0.11.1", optional = true }
minify-js = { version = "0.5.6", optional = true }
mdtrans = { git = "https://github.com/litchipi/mdtrans.git" }

[dependencies.syntect]
version = "5.1.0"
features = [ "html", "regex-onig", "default-themes", "default-syntaxes" ]
default-features = false

[features]
default = ["local_storage"]
dev = ["local_storage", "hot_reloading", "no_cache"]

local_storage = []

minify = ["css_minify", "html_minify", "js_minify"]
css_minify = ["lightningcss"]
html_minify = ["minify-html-onepass"]
js_minify = ["minify-js"]

hot_reloading = []
no_cache = []

[profile.release]
opt-level = 3
strip = "symbols"
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 16

[profile.dev]
codegen-units = 425 # 250
