on:
  pull_request:
    types: [ opened, edited, closed, reopened, synchronize ]

jobs:
  check:
    runs-on: docker #rust-1.75.0
    steps:
      # - run: "curl -fsSL https://deb.nodesource.com/setup_21.x | sudo bash - && sudo apt-get install -y nodejs"
      - uses: https://code.forgejo.org/actions/checkout@v4
      # - run: cargo check
      # - run: cargo clippy
      # - run: cargo fmt --check
      - run: cat Cargo.toml
